### ISSUE TITLE
App icons not changing based on size selection

### ISSUE THREAD

**Issue by Judman** [revenz/Fenrus#10]
I set app icons to different sizes and the icons do not change as expected. The only app that changed was Jellyfin and the form factor is not ideal. Group and icon size noted in screen shot.

I am on version 0.1.0.110 installed through Unraid Community Apps.

![image](https://user-images.githubusercontent.com/3705824/155741566-0a3fd177-da81-49dd-b848-0518b1920584.png)

**Comment by revenz** [comment]
the theme has to support different sized items, if they don't (heimdall and basic theme) then they wont change size.

the non default themes won't get much attention for now, still fleshing out features.

**Comment by revenz** [comment]
I've made some minor tweaks to the basic theme
small is same size as medium, but show now stats
large, xlarge, xlarge are all slightly bigger than each other.  

I've also updated the "preview" when adding an item for the basic theme and heimdall theme to show what they will look like.

I'm hoping to get this version out by the end of the weekend, just been busy trying to tweak the default theme tile placement.

I was surprised to see someone using this the basic theme.  

small:
![image](https://user-images.githubusercontent.com/958400/155831331-60a35800-ee20-4958-965c-42ba14acdbaf.png)

medium:
![image](https://user-images.githubusercontent.com/958400/155831311-463388f1-2e4f-42d9-a38b-a96336e3fef6.png)

large:
![image](https://user-images.githubusercontent.com/958400/155831336-3803ca6e-a71b-4220-8e8c-c0003449555b.png)

xlarge:
![image](https://user-images.githubusercontent.com/958400/155831341-1f51a243-12e4-4c33-90c7-79be4f25bb8a.png)

xxlarge:
![image](https://user-images.githubusercontent.com/958400/155831348-0bffd393-db04-48b3-8254-5bfddcf2629b.png)

**Comment by Judman** [comment]
I did not even realize I had changed from the non default theme. I will change that and play around with sizes.

Thanks for the response!
