### ISSUE TITLE
[Feature Request] Status Indicator

### ISSUE THREAD

**Issue by MayhemBill** [revenz/Fenrus#112]
I recently swapped to Fenrus from Dashy for the Smart Apps you have, but one feature I miss is seeing the status of a website from the main dash board, Dashy used a small dot on the upper corner for indication, red for errors, yellow for timeout, green for work, and grey for unreachable, would it be possible to implement something like this in Fenrus?

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/185713680-c107c141-0292-4779-856e-c906ad3d457b.png)

this has already been added to the next version.   not exactly the same.

It will fade out any app/link that is "down".

**Comment by MayhemBill** [comment]
That also works just as well, kind of a cool concept too, when will this version be released?

**Comment by revenz** [comment]
when its done. no eta atm.
