### ISSUE TITLE
Feature request - Smart app info box provide description of functionality

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#116]
As a user i would want to know what functionality a smart app would provide if I were to input my properties into it.
As such a short description should be able to be provided within the "Info" section of the app.json alongside Author and AppUrl Section

**Comment by revenz** [comment]
added, FileFlows app is the only app that currently uses this, but just update a app.json to include the info.

For example 

```json 
{
  "Name": "FileFlows",
  "TestFunction": true,
  "Interval":5,
  "Icon": "icon.svg",
  "Info":{
    "Authors": ["John Andrews"],
    "AppUrl":"https://fileflows.com/",
    "Description": "Shows information from FileFlows including files that are currently processing, files that have been processed.\n\nCan show a carousel for currently processing files.  Bar charts for processed files, or basic information if the size of app is set to medium."
  }
}
```
