### ISSUE TITLE
Fix Status up checker to check redirects

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#122]
Currently, if an application URL has a redirect it gets registered as offline 

Example:
http://gaps.home/
to
http://gaps.home/libraries 
Since / redirects to /libraries but fenrus was showing it as offline
Example of redirect seems to be based on 'location'
![image](https://user-images.githubusercontent.com/77850077/187053137-5ff9c661-c2f5-4585-abc7-5870953a6c6b.png)

was reproduced with the app Gaps
https://github.com/JasonHHouse/gaps

**Comment by revenz** [comment]
is this still happening?  or was it in the old node app only?
