### ISSUE TITLE
FR: Display currently streams on Tautulli like plex app

### ISSUE THREAD

**Issue by hbooo** [revenz/Fenrus#125]
Currently Tautulli is displayed like this : 
![image](https://user-images.githubusercontent.com/242125/187617137-77360586-81ac-403f-9862-84d7add94360.png)

I would like to have an option to display a banner instead of just the count to be able to see what is streaming.

Something like this : 
![image](https://user-images.githubusercontent.com/242125/187617966-2bf0e242-90c1-4a8b-acdd-5f1812483fa7.png)

**Comment by revenz** [comment]
Good idea, next version


![Image](https://user-images.githubusercontent.com/958400/188251837-b07b4491-54e7-4cd5-b642-fa22cdb561e7.png)
