### ISSUE TITLE
FR: Display Total Storage Saved for FileFlows app details

### ISSUE THREAD

**Issue by hbooo** [revenz/Fenrus#126]
Currently FileFlows app display queue and currently running process 
![image](https://user-images.githubusercontent.com/242125/187873378-954b8d09-b7a4-409b-bd5e-ad13f6eed146.png)

It could be great to have an overview of Storage Saved from app : 
![image](https://user-images.githubusercontent.com/242125/187873758-25ceebed-76f7-4453-a0cd-deaa20aa66bd.png)

**Comment by revenz** [comment]
went a different way with fileflows.
