### ISSUE TITLE
oAuth2 - Groups?

### ISSUE THREAD

**Issue by Smith-fms** [revenz/Fenrus#134]
Hey!

I got some strange problems. I use fenrus with keycloak IDP. Login is working but there a few questions.
1) the first account is admin. I setup a dashboard but the next "normal" user didnt see it. 
2) is ist possible to get a group from Keycloak to fenrus? Like "Group1" -> Dash 1, "Group 2" -> Dash 2?
3) is anybody using fenrus with keycloak? :-)

Thanks for this Project!

Greetings/Grüße

Rene

**Comment by revenz** [comment]
closing as nothing to do.   support questions post in the discord
