### ISSUE TITLE
Feature Proposal - LDAP Authentication Strategy

### ISSUE THREAD

**Issue by thiagobucca** [revenz/Fenrus#139]
Hello, 

I've implemented LDAP authentication on Fenrus and would like to know if this is something you guys are interested in merging with the main code. If this is the case, i'll be happy to send a PR for this.

Thanks in advance.

**Comment by revenz** [comment]
sure put in a pull request and I'll take a look

**Comment by thiagobucca** [comment]
PR opened :)

**Comment by revenz** [comment]
yeah, sorry this conversation happened before I decided to rewrite fenrus in dotnet.  So I'm going to reject the PR.  that branch is effectively dead.

**Comment by thiagobucca** [comment]
sure, no problem, actually the delay was all on my side to open the PR. Anyway, i'm looking forward to the dotnet branch. Thanks
