### ISSUE TITLE
Docker command fails

### ISSUE THREAD

**Issue by TangledWiresYT** [revenz/Fenrus#141]
The command to install using docker gives an error

unknown shorthand flag: 'n' in -name=Fenrus-p
See 'docker run --help'.
-bash: --restart: command not found

**Comment by diablo668** [comment]
The docker run example cmdlet in the README.md is missing a few bits, it should be:
docker run -d \
--name=Fenrus \
-p 3000:3000 \
-v /path/to/data:/app/data \
-v /path/to/images:/app/wwwroot/images \
--restart unless-stopped \
revenz/fenrus:latest


--name=Fenrus \ in stead of -name=Fenrus\ and -v /path/to/images:/app/wwwroot/images \ in stead of -v /path/to/images:/app/wwwroot/images

**Comment by TangledWiresYT** [comment]
> The docker run example cmdlet in the README.md is missing a few bits, it should be: docker run -d --name=Fenrus -p 3000:3000 -v /path/to/data:/app/data -v /path/to/images:/app/wwwroot/images --restart unless-stopped revenz/fenrus:latest
> 
> --name=Fenrus \ instead of -name=Fenrus\ and -v /path/to/images:/app/wwwroot/images \ instead of -v /path/to/images:/app/wwwroot/images

Ah, thank you. I am quite new to docker
