### ISSUE TITLE
Feature Request - Change Page Title and Favicon

### ISSUE THREAD

**Issue by LarveyOfficial** [revenz/Fenrus#142]
It would be great to be able to change the page title and favicon, the favicon doesn't match what I currently have as my theme color, and it would be great to be able to change it, same with the title of the page (what shows in the tab)

**Comment by revenz** [comment]
I'll update it so the page title is the dashboard name, and make it so the favicon svg uses the theme color/dashboard color.

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/210742169-8ef2a81e-51a2-45bd-8719-fda69f883cb9.png)

done in the dotnet rewrite
