### ISSUE TITLE
Feature Request - Allow editing GUEST dashboard

### ISSUE THREAD

**Issue by jaywehner** [revenz/Fenrus#143]
Would like the ability to change the default GUEST dashboard. when nobody is logged in it shows a guest page with links. Is it possible to change this to a different dashboard or edit this? I want to make one that shows specific social media sites and other popular links.

**Comment by jaywehner** [comment]
Well I found a work around. You can edit the system.json file and change the Items and Groups as needed. But if you don't know json I don't advise this :)

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/210646822-b693af45-ff24-4e1d-8d3c-b537450790dc.png)

as an admin user there is a config section for the guest dashboard.  if youre not seeing that, then youre not an admin user.

**Comment by jaywehner** [comment]
Thank you for the clarification! I'm an idiot and I can admit it. I was using my test account not the admin
