### ISSUE TITLE
Feature Request - Save last type when adding new items to group

### ISSUE THREAD

**Issue by permster** [revenz/Fenrus#144]
Somewhat related to #68, but can you add an option or make it default to remember the Type you last selected when adding new items to a group?

So for example, if I have the keep open option enabled and I save a link type item to the group it should clear the fields like it does now but leave the Type set to what it was previously which was "Link".  It's a bit tedious having to change the Type over and over again when adding a long list of the same type of item.

**Comment by revenz** [comment]
in the dotnet rewrite I'm currently working on, it now does this.

when adding a new item, if "Keep Open" is checked, only key fields are cleared, the rest remain the same as the previously entered fields.
