### ISSUE TITLE
qBitTorrent "Unauthorized" when Launched from Fenrus

### ISSUE THREAD

**Issue by Obsidiannite21** [revenz/Fenrus#151]
Its odd. If I put in the ip Manually (192.168.x.x:port) or click on a bookmark I can access qBittorrent without issue from any device on the network. However, if I try to access qBittorent via a Fenrus shortcut it displays "unauthorized" and nothing more. I ONLY get that error when launching from Fenrus. I've researched the error and tried to troubleshoot it from the config / qbt side but I wasn't able to resolve the issue. Any ideas?

Type: app (tried link as well)
App: qBittorent
Target: default (tried iframe as well)
URL: http://192.168.x.x:port

**Comment by revenz** [comment]
does this still happen on the dotnet version of Fenrus?

**Comment by Obsidiannite21** [comment]
I'm not sure, I'm using the docker / ARM build.
