### ISSUE TITLE
Request: Notes

### ISSUE THREAD

**Issue by PrzemekSkw** [revenz/Fenrus#152]
Fenrus is my command center and something that is missing is some notes card where I can put some temporary notes so I don't have to open notes app.

Regards.

**Comment by revenz** [comment]
How do you imagine this being implemented?

- A dedicated "Notes" app that you can add to a group, then it would be whatever size you configured (medium, large, larger etc).
- Or, floating notes with a delete icon?
- a popout panel for notes?
- a dedicated page?
- would you want this persistent across computers,  or would saving to localstorage so only that browser has access to it sufficient? 

I'm thinking a side pane on the left that can open up, saving that to the database.  then it comes down to notes per dashboard or same notes for all dashboards....

**Comment by revenz** [comment]
added in dotnet version, and available in that now
![image](https://user-images.githubusercontent.com/958400/229956380-65f85d90-133e-4695-a5d1-b5cbdb2895e4.png)

**Comment by PrzemekSkw** [comment]
Hi, @revenz that's great. I didn't expect such good solution.
Regards.
