### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Sf298** [revenz/Fenrus#159]
Hi there! I believe there might be a memory leak somewhere on the server. 
I just looked at the RAM usage and it was about 500MiB. A friend of mine also had 700MiB.
After a restart it dropped to 70MiB and is slowly ticking up.

I am on the latest version of dotnet, and it is a fairly fresh install.

**Comment by Frooodle** [comment]
![image](https://user-images.githubusercontent.com/77850077/230640550-d9e7ed8f-9673-4cdb-af28-b4d33d22dc37.png)
2.7gb now
refreshed another 5 timses and reached 2.8GB
keeps going up
![image](https://user-images.githubusercontent.com/77850077/230640757-7c435d96-f8d3-4145-9c25-8efeab8e6744.png)
