### ISSUE TITLE
Default option overrides all options

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#16]
The default option when you edit a app is always present even once you input your own value

Recreate : Create GOG app, 
edit Country from NZ to GB
save and open edit again.
Shows NZ not GB

**Comment by Frooodle** [comment]
(The GB value is saved, but you can never view it in edit second)

**Comment by revenz** [comment]
move to New Zealand?  Its very lovely.

**Comment by revenz** [comment]
fixed this now.  but for some reason the first item in gog the default value is always shown blank...  on edit it's not.  I have to look into this later.
