### ISSUE TITLE
Randomly very low image resolutions in apps

### ISSUE THREAD

**Issue by nameproof** [revenz/Fenrus#162]
Version
0.9.0.889

Apps in dashboard pull in very low resolution images. According to dev it currently scrapes Google images which is the cause. 

![image](https://user-images.githubusercontent.com/38396467/233206865-7dc7edfd-ff37-4ab3-8f5e-b1bf99f32f6c.png)

A suggestion is using TVDB and/or TMDB instead. Could also cache them if you want to go overboard.

**Comment by nameproof** [comment]
For what it's worth, if you want to prioritize other stuff it would be nice to be able to toggle off background image in the app. As a quick fix while it's this low res. This very low res is making the dashboard look very low quality compared to all the other nice things :)

**Comment by revenz** [comment]
you can just change the size of the app to now show the carousel/images

**Comment by nameproof** [comment]
> you can just change the size of the app to now show the carousel/images

Understood but then I miss out on the history.
