### ISSUE TITLE
Groups are bugged

### ISSUE THREAD

**Issue by Kurotaku-sama** [revenz/Fenrus#165]
There are several bugs in the groups

In the Personal Dashboard:
- When you click on the Group Name you are Refered to "<domain>/settings/groups/<groupid>"
- But when you click on the edit icon on the right side it leads to "<domain>/settings/dashboards/<groupid>"

This triggers the console error:
_Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'._ 
And than all other links on the page won't redirect you anymore till your reload the page

The second bug is in the Guest Dashboard:

![grafik](https://github.com/revenz/Fenrus/assets/54163348/746fde62-81ce-48fc-81a5-e8e5a52cab03)

Even tho this 2 are my personal groups they are able to get added to the Guest dashboard I guess that shouldnt be able to work like that.

And the third bug in the System Groups:
When I add a System group the Group is added to the personal Groups not the System Groups.
Since I cant test if there are also redirect errors on the icon I cant say if there are more bugs on this sites at the moment

**Comment by revenz** [comment]
already fixed the first one.

split this into separate issues, one issue for each issue
