### ISSUE TITLE
Feature Request - Automatically update groups after edit

### ISSUE THREAD

**Issue by jvelder** [revenz/Fenrus#167]
Hi,
been using the dashboard for a while. Something that's been bothering me for a while is, when I add/edit/delete entries in a (system) group, I have to manually dis- and enable them in the dashboard settings for the changes to take effect.
Just checked, and even a forced reload of the dashboard inside my browser does not update the groups, so it seems to be on Fenrus' side.

Thanks!

**Comment by revenz** [comment]
what version?  0.5.0 and below (ie the node version) or 0.9.x (the dotnet version)

**Comment by jvelder** [comment]
Hi,
sorry for the delay in answering.
It's the old version, in the meantime I switched to the rewrite & there it works.
Closing the issue then. :)
