### ISSUE TITLE
update oauth2 and font/icon size

### ISSUE THREAD

**Issue by rswafford1980** [revenz/Fenrus#169]
can you remove the readonly option from the oauth2 callback url so it can be edited correctly? Also, is there a way to give options to update the font size and have the icon size truly show what size you've picked? the font on my screen is extremely small and hard to read, and the icons give a larger area, but everything in them is the same size no matter which one you choose.

**Comment by revenz** [comment]
1. no this cant be editted, its part of the openid connect library I use, its what it expects.   you should be able to set the callback url on your auth server to this url (google and auth0 you can)
2. screenshot?

**Comment by rswafford1980** [comment]
1. the problem is, it is using http not https. yes, I can set the callback url on my auth server to what is listed; however, since everything I'm using is https, the http callback will not work. I'm not sure where it's getting the redirect url from, but it prevents me from using openid connect. 
2. I'm using the basic view, here is a screenshot. 
![Screenshot 2023-05-21 at 3 14 23 PM](https://github.com/revenz/Fenrus/assets/129755104/30ade290-3e8a-492e-a1b0-2441a27615aa)

**Comment by revenz** [comment]
ah basic theme, thats basically there just to show people how to make a new theme.  it doesnt support different sized icons, currently the only theme that does is the default theme.  feel free to make a new theme
