### ISSUE TITLE
Import old configuration

### ISSUE THREAD

**Issue by RafalHo** [revenz/Fenrus#171]
Hello,

I updated Fenrus to the latest version and unfortunately all the previous setup with users and my shortcuts on the main page is gone.
Is there any possibility to import users and shortcuts to the new version?

Thanks in advance for the info.

**Comment by revenz** [comment]
yes there is a guide on the wiki

https://github.com/revenz/Fenrus/wiki/Upgrading-from-Fenrus-0.5.0-and-below
