### ISSUE TITLE
Can't import config after update

### ISSUE THREAD

**Issue by RoryNesbitt** [revenz/Fenrus#172]
I followed the instructions to download my config, then I updated to the newest version
I can change the tabs in settings to each different page but none of the buttons in them do anything, meaning I can't click import config.
Forms work but other things that are broken include adding a group or changing a tab in the page (e.g. password on the users page, etc )

I am running fenrus under unraid and I've cleared the appdata folder and done a fresh install

**Comment by vger74656** [comment]
I've had the same issue.  Restored config folder in docker and goes back to initial user creation screen

**Comment by revenz** [comment]
there was a bug in the intial release, download the latest docker image and follow the wiki instructions

https://github.com/revenz/Fenrus/wiki/Upgrading-from-Fenrus-0.5.0-and-below
