### ISSUE TITLE
Import from NodeJS to NET

### ISSUE THREAD

**Issue by vger74656** [revenz/Fenrus#173]
Hi,

Just did the upgrade from preview to latest and attempted to import the config.  It came up with the below.

![image](https://github.com/revenz/Fenrus/assets/10250310/f6ae432b-0567-40c3-a559-f2fb48af85b4)

I've tried it by both deleting the old docker data folder as well as simply starting the container over the top of the preview version.  In both attempts it won't import.

I have reviewed the .json file and the contents appear to be valid.  If you want me to upload this, i'm going to have to redact some lines for security reasons.

Am I doing anything wrong?

**Comment by vger74656** [comment]
Sorry I meant I've tried to upgrade, as well as doing a fresh install and then importing the config, both times came up with the same screenshot outcome.

**Comment by revenz** [comment]
i need the config file to try and import it and see what errors  you are getting.

**Comment by vger74656** [comment]
[Fenrus-6_4_2023 - Copy.txt](https://github.com/revenz/Fenrus/files/11649287/Fenrus-6_4_2023.-.Copy.txt)

Please remove from ticket when downloaded.  It doesn't contain any passwords, but I'd prefer for this not to be in public view.

**Comment by revenz** [comment]
k, thats not the exported system config, thats your users config file.  thats why the import fails.  you have to export the entire system config then import that.   

you can delete the attachment now

**Comment by vger74656** [comment]
OK, where can I export the system config?  I can't see anywhere else to export it.

![image](https://github.com/revenz/Fenrus/assets/10250310/bece7fb9-3452-48f7-965a-6b48d504ff0b)

According to the documentation, it should be in that window.  But the only place I can see an Export option is in the General tab.

**Comment by vger74656** [comment]
I really love this app by the way, and your responsiveness in supporting us dummies :)

**Comment by revenz** [comment]
https://github.com/revenz/Fenrus/wiki/Upgrading-from-Fenrus-0.5.0-and-below

**Comment by vger74656** [comment]
Yeah, I followed that, but the Export option isn't in the About tab.  Is 0.5.0.460 the version with the export option?

**Comment by revenz** [comment]
You have to login with an admin account to see that page

**Comment by vger74656** [comment]
This is the only account.  Is there a way of setting it as an admin, or resetting a built in admin user?

**Comment by vger74656** [comment]
Never mind, figured it out.  I now have export options.  Thank you for your help!
