### ISSUE TITLE
Lockup trying to edit groups

### ISSUE THREAD

**Issue by skaterpunk** [revenz/Fenrus#178]
Go into settings on left side click groups, click any group to edit. It does not go into the group for editing. It seems to lock up Fenrus nothing else clicked responds even clicking home. Have to refresh browser to get and navigation back. It does seem to work however if on the left column dashboards is selected, for me i edit the default dashboard. From there if a group is selected to be edited it works as it should, you can add and/or change apps or links. Upon saving it puts you into the groups on the left column and locks up if another group is selected from there to be edited.

**Comment by revenz** [comment]
cannot reproduce
1. fresh install on unRAID, no fenrus data directory existing on creation
2. create login
3. login
4. click settings page
5. go to "Groups" page
6. added a group
7. added a new item ot the group
8. saved group
9. went to dashboard page
10. added new group to default dashboard
11. saved dashboard
12. went to "Dashboard" page (ie the main page)
13. new group with new item there

**Comment by permster** [comment]
I think I'm seeing this issue or something similar to it on a fresh install, version 23.06.3.985.  Do you want me to open a new issue for it?

If I mouse over the group name on the left hand side it gives me this link:
http://192.168.X.X:3000/settings/groups/2d7eb29b-f2be-48a7-9c87-a29f0aa11993

But if I mouse over the little edit icon on the right side it's giving me this link:
http://192.168.X.X:3000/settings/dashboards/2d7eb29b-f2be-48a7-9c87-a29f0aa11993

Clicking the group name on the left works fine but clicking on the edit icon on the right causes the lock up and subsequently the need to refresh the page to get things working again.
