### ISSUE TITLE
Not able to create system groups v23.06.1.976

### ISSUE THREAD

**Issue by makuris** [revenz/Fenrus#179]
I freshly installed the latest version and tried to recreate my groups.
Dashboard > Groups works just fine.

I then wanted to add System Groups, if I  create a group there and click on save the new group is saved and appears unter the Dashboard > Groups again. 
The Administrator > System Groups section stays empty and there is no system group created.

**Comment by revenz** [comment]
cover by other closed issues, and by this wiki upgrade instructions

https://github.com/revenz/Fenrus/wiki/Upgrading-from-Fenrus-0.5.0-and-below

**Comment by revenz** [comment]
fixed
