### ISSUE TITLE
Open in a new Tab function not korrect?

### ISSUE THREAD

**Issue by Lucifor1976** [revenz/Fenrus#182]
My Setup is open links i an new Tab.
But Fenrus only uses one Tab. Open next link will overwrite the last new Tab. Is it correct?

For me better works always open a new Tab. Can you make it configurable?

Example: Click on any link opens a new Tab, clicking another link in Dashboard the opened Tab will used for it. Thats Bad. (for me)

Greezt and really good Work :)

**Comment by makuris** [comment]
I seem to have the same issue. The two options "open in new tab" and "open in same tab" are acting both like "open in same tab" in the latest release 23.06.1.976

**Comment by revenz** [comment]
Fixed in next version
