### ISSUE TITLE
Remove red border for endpoints which have monitor disabled

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#189]
Remove red border for endpoints that have monitor disabled. since its implied that if not monitored its uptime might not be constant

**Comment by revenz** [comment]
the red board isnt for up-time its for update status,   meaning it tried ot do an update status, for smarts and it failed.

**Comment by revenz** [comment]
added css check for [x-monitor='1'] so this will only appear for monitored apps now
