### ISSUE TITLE
[Feature Request] Allow smart apps to have different URLs for use in their API vs their redirects

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#20]
Allow smart apps to have a optional different URL for use in their API vs their redirects from main UI

Meaning if you clicked on it, it would send you to x domain, but API would query against y domain.

**Comment by branchmispredictor** [comment]
+1 to this. Just to share a use-case: All my services are behind an https reverse proxy that requires auth. If Fenrus tries to hit these endpoints, it will get denied. I would like to pass in the machine-local address instead of the end-user-facing address for api access.

**Comment by revenz** [comment]
fixed, will expose "API URL" for smart apps in the next release.
