### ISSUE TITLE
Errors when connecting to apps

### ISSUE THREAD

**Issue by Feramance** [revenz/Fenrus#207]
I've been setting up my Fenrus dashboard however I've noticed a few apps with connection issues to APIs. Prowlarr and Tautulli are giving me a `console not defined` error, Fileflows is giving and an `INFO undefined`, Plex is giving me a `Test Failed` error and I expected qbittorrent to use the API to show some info, but nothing comes up.

**Comment by revenz** [comment]
cant repo the console not defined issue.  testing tautulli on my install and test works fine.  checked the code for both, neither even mention "console".  what version are you on?

qbittorrent, is a basic app, no one has made it a smart app yet, so thats not a bug, someone would need to submit a PR to make it a smart app

**Comment by Night2512** [comment]
Sorry to open this again.
I'm having the same issue with Prowlarr, Tautulli and Plex when testing the API connection.

Deployed Fenrus from revenz/fenrus:latest docker container.
Prowlarr: 1.7.4.3769
Tautulli: 2.13.1
Plex: 1.32.6.7557

Happy to provide any logs required.

On an additional note, PiHole doesn't load data from API and there is no Test button when adding the app.
