### ISSUE TITLE
Paypal donation broken

### ISSUE THREAD

**Issue by SergioZgz** [revenz/Fenrus#208]
Hi,

I discovered this week your dashboard/homepage and I really love it, I want to donate something to you so you can at least have a few coffees to my health, but the paypal button doesn't work properly, please fix it :)

**Comment by revenz** [comment]
paypal changed the way they do donations, only charities can accept donations now.   so i removed the paypal link.   easiest way to donate now would to just join patreon and cancel it for a once off.,  that gives you benefit of fileflows premium features too

**Comment by SergioZgz** [comment]
Perfect, then I will use Patreon, thanks for clarify it, and keep good work :)
