### ISSUE TITLE
No export function available anywhere

### ISSUE THREAD

**Issue by gemorgan** [revenz/Fenrus#215]
Running Fenrus Version: 23.08.3.994 in docker on Unraid. Image comes from repo revenz/fenrus. Looks like from older posts that an export function is supposed to be available on the About page to export configuration and previous suggests mentioned this could be used to transfer groups and dashboards from one user to another. I can't test that, because there is no export anywhere. The version numbers in the older posts and on the wiki are are 0.5 ish and 0.9 ish and the version listed on my instance of Fenrus isn't even in that format.

**Comment by revenz** [comment]
already answered this on closed ticket.

the export function was to export legacy fenrus configuration to import into current fenrus.  

anything starting with a version 0, is legacy fenrus, anything 1 or up, current version is 23.08, doesnt need this.  the configuration is a single file you can just move into your  data directoryy for backup/restore.
