### ISSUE TITLE
Node file & folder permissions

### ISSUE THREAD

**Issue by Phil-Barker** [revenz/Fenrus#223]
I'm not sure if I'm misunderstanding something here but I have my fileflows pick up files from `/downloads/complete`, convert to H265 and other stuff via a flow, and at the end of the flow moves files to `/downloads/converted`

Problem is every folder it creates in `/downloads/converted` is 755 and every file is 644
I have been into the node -> advanced and changed file permissions to 664 which doesn't seem to do anything
Every time I set folder permissions to 775 it just goes back to 755 greyed out?

Fileflows is running in a docker container on unraid if that makes any difference.
I've checked the incoming files in `/downloads/complete` and they have the correct permissions, it's just after they're moved the permissions are wrong.

It's really  annoying as then sonarr/radarr don't seem to be able to pick them up, and I can't do anything with them from my windows PC over a samba share

**Comment by revenz** [comment]
This is the fenrus project.

Jump on the fileflows discord and create a support thread in there.
