### ISSUE TITLE
Fenrus does not fully support laptops/small resolutions

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#23]
When running fenrus in 1080p 100% scaling I can edit this fine
![image](https://user-images.githubusercontent.com/77850077/156656230-30c6f75b-f8d9-419a-a038-09c3ddd4c1c3.png)

However if i got to my laptop which is 1080p 125% scaling it shows like this
![image](https://user-images.githubusercontent.com/77850077/156656334-47b8f087-3d47-4987-8f96-639b73cb454a.png)

Hiding the save button and with no scrolling it makes it unusable 

Work around for now is to try different monitor or adjust scaling

**Comment by revenz** [comment]
already fixed, will be in next release.

**Comment by Frooodle** [comment]
thats fast

**Comment by revenz** [comment]
fixed it yesterday when i saw it :P
