### ISSUE TITLE
[Feature Request] Allow the ability to change app icon from within code.js 

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#26]
When making a Minecraft server smart App within Fenrus I became aware that the API exposes the image that's setup for that server.
This image is in base64 format.
(https://api.mcsrvstat.us/2/us.mineplex.com is example api call with icon being under root.icon) I had thought of auto applying it to the app so if the remote server ever updates its icon the local Fenrus icon would also auto update along with this. 

When saving the icon to  __dirname + '/dynamicIcon.png'
and then setting args.appIcon to this dir results in nothing changing as this appIcon  seems to get set back to original value.

Would it be possible to provide a method to change this icon from within the apps code either with path input or base64 input? 

Minecraft server icons look like this for context
![image](https://user-images.githubusercontent.com/77850077/156863363-65a2d4ff-c3f7-4ee1-b3e3-79060bedf535.png)

**Comment by revenz** [comment]
added this method
```
args.changeIcon('https://logovector.net/wp-content/uploads/2012/05/318009-batman-20-logo.jpg');
````
It sets a special header in the response that the front end will look for, that is base64 encoded (to avoid header character restrictions).  I wouldn't use a base64 image here though, chances are that would be too big for the header.

Let me know if this is sufficient.

**Comment by Frooodle** [comment]
Seems to work, closing issue :)

**Comment by Frooodle** [comment]
@revenz  Do you think you could get this change icon cached? it seems to reset as soon as I press F5 etc
