### ISSUE TITLE
[Feature Request/Bug] App Design on Heimdall Theme

### ISSUE THREAD

**Issue by fscorrupt** [revenz/Fenrus#38]
On Default Theme the Steam store or Plex has pictures and updates itself, if i switch to Heimdall Theme they dont ..
Is this a Bug?

Default:
![image](https://user-images.githubusercontent.com/45659314/157240111-c2fa3766-6ed4-4673-92bb-df46837ed600.png)

Heimdall:
![image](https://user-images.githubusercontent.com/45659314/157240179-fe3fc59d-ba9a-4fa5-bdbf-76566f5d9e17.png)

**Comment by revenz** [comment]
nah as designed.   It matches the look of Heimdall which doesn't have a carousel/image preview thing.
