### ISSUE TITLE
Feature request Retrieve header/cookies

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#42]
As a user i want the ability to develop apps that require extra info outside of just JSON such as cookies or headers. 

Currently the only way of grabbing the response object itself to grab headers/cookies/ResponseCode from that response is by changing the 'Accept' header to be something other than JSON (was done to allow for xml code at time). But this usecase of requiring access to headers/cookies can still apply to queries using a "Accept": "application/json" etc

**Comment by revenz** [comment]
theres nothing stopping you from using just "fetch" instead of "args.fetch".  args.fetch just makes "fetch" a little easier to use with relative to absolute URL etc.   so you should be able to achieve what you are after by just using "fetch" directly.

**Comment by Frooodle** [comment]
sounds fine to me
