### ISSUE TITLE
Fenrus  Launching Smart App

### ISSUE THREAD

**Issue by damda58** [revenz/Fenrus#44]
I loaded the latest update and now when I click on a smart app's tile it opens fine in a new tab as requested, but the fenrus tab gets stuck with Launching

![image](https://user-images.githubusercontent.com/6893451/158012991-78bf6951-6229-41d1-9c79-271f2a79edb6.png)

**Comment by revenz** [comment]
Fixed.   Removed this "splash" if the target is not set to "Open in this tab".
