### ISSUE TITLE
List and progressBar on Smart App

### ISSUE THREAD

**Issue by damda58** [revenz/Fenrus#54]
would it be possible to 'easily' add a Smart app return consisting of progressBar AND list?
As the following picture

![image](https://user-images.githubusercontent.com/6893451/158675608-5cd11ca8-3b69-480c-92e2-a83ba345f7f4.png)

**Comment by revenz** [comment]
Done.   If you add an item like this
```
{
      label:'Up Time', value: uptime
}
```
to the list of items for barinfo, it will look for the "value" property and if found display it like this
![image](https://user-images.githubusercontent.com/958400/158883499-b65a7da6-7a6f-4bce-822b-00204a3ec6ef.png)

See the Glances app for a working example
