### ISSUE TITLE
Center or adapt the content of the tiles?

### ISSUE THREAD

**Issue by damda58** [revenz/Fenrus#59]
On a large tile if the space is larger than the content, it is not centered

![image](https://user-images.githubusercontent.com/6893451/158975160-eaccfcd9-ca3c-472c-bcf9-5363106f0288.png)

**Comment by revenz** [comment]
My initial thought here is that this can then cause a problem if the content is larger than the area.  If centered, it will stay center and you will have content cut off from both the top and the bottom.   

I'll leave this open until I have a chance to explore options, but I believe I tried this previously and had that issue so I removed it.
