### ISSUE TITLE
Uploaded Icon of Link not shown if used in system group

### ISSUE THREAD

**Issue by makuris** [revenz/Fenrus#65]
Hi everyone, 

I have just started exploring Fenrus and already like this tool.

I created a system group containing some links and uploaded my own icons (PNG) using the browse button. The icons do not load if it is a system group - see screenshot. If I add the same link/icon to a group (not system) then it works and the icons are shown.
![error1](https://user-images.githubusercontent.com/43435080/160621908-469489e8-9a66-4836-a5bb-7f8d82b5dd0e.png)

Is this a bug or am I missing something?

**Comment by revenz** [comment]
fixed in 0.4.1
