### ISSUE TITLE
Reset fields or close the sidebar after adding a new item in a group

### ISSUE THREAD

**Issue by StefanescuCristian** [revenz/Fenrus#68]
Hi,

Not a bug, more like an UX "issue".
Is there a way to reset the fields or close the sidebar after adding a new item in a group?

What I'm expecting is:

1. Go to groups, create a new one or select an existing group.
2. Add a new item (App or Link, I haven't tested with a dashboard but I think the behaviour is the same)
3. Input/Select your fields (App name, Link URL, etc)
4. Click save. The item is now added to the group.
5. Reset the fields so the user can start fresh or let the user click outside of the right sidebar to close the sidebar, or autoclose the sidebar.

What happens:

1. Go to groups, create a new one or select an existing group.
2. Add a new item (App or Link, I haven't tested with a dashboard but I think the behaviour is the same)
3. Input/Select/Edit your fields (App name, Link URL, Title, etc)
4. Click save. The item is now added to the group.
5. If you select a Link, the fields remain the same after clicking the save button. If you select a (new) app, the fields reset, which is fine (sort of), but when you click the save button the newly added item is overwritten with the new fields that you inputed.

**Comment by revenz** [comment]
Added to version 0.4.1

When Adding new items (not when editing existing items) there is now a switch to keep the editor open.

![image](https://user-images.githubusercontent.com/958400/161405712-56d91d7e-509f-45e3-8e64-b0344c81a7c8.png)
