### ISSUE TITLE
Copy inside the same group

### ISSUE THREAD

**Issue by StefanescuCristian** [revenz/Fenrus#69]
Hi,

Is there a way to copy an item into the same group?

For example I run 3 separate instances of Pihole. I want to add the 3 instances into the same group.
I can't seem copy the first item into the same group, now I can only add it again via the sidebar.

I think that this will be a nice enhancement to the UX if it can be implemented.

**Comment by revenz** [comment]
Added in 0.4.1
New option at the top of the copy to that shows this group
![image](https://user-images.githubusercontent.com/958400/161405459-bfa12eaa-1ead-449c-ade5-f449f85de515.png)
