### ISSUE TITLE
Not able to add custom icons for apps already in list.

### ISSUE THREAD

**Issue by nirav72** [revenz/Fenrus#7]
I have two Pihole instances. So wanted to set distinct icons for each instance.  I selected Pihole as the app and uploaded a custom icon for one of the pihole instance.  The icon did not update.  I even tried to copy the icon png file to the /images directory and then manually attempted to set the path in the json configuration. No luck.

**Comment by revenz** [comment]
fixed in Version: 0.1.0.83
