### ISSUE TITLE
Request : have the login page as the default guest dashboard

### ISSUE THREAD

**Issue by Jayknightfr** [revenz/Fenrus#72]
I'm loving this app and use it as the homepage of my private website and would like to greet the visitors (mainly me and my family) to the login page directly, is it possible to add this feature ?

**Comment by revenz** [comment]
possible.  but not sure if this would be an overall worse experience for users.   if you enable the "Guest" dashboard, going to the root will show you that dashboard if not signed in.  If disabled going to the root if not signed in will do a redirect.

To make it work so always goes to the login page even if the guest is enabled, the dashboard would then have to become a non-root URL, eg /dashboard.   and / would redirect to /login or /dashboard depending on logged-in status/configured setting.

**Comment by Jayknightfr** [comment]
Oh so I just have to disable the guest dashboard, perfect thanks!

Le sam. 9 avr. 2022 à 10:38, John Andrews ***@***.***> a
écrit :
