### ISSUE TITLE
Ctrl click for new tab support in "Open in this tab" mode

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#83]
As a user I would want the versatility of being open a window in the same tab or new tab by using ctrl click on the item.
Currently this works as expected if you do right click open as new tab but if you ctrl + click
It will permanently show the 'Launching' Screen overlay
![image](https://user-images.githubusercontent.com/77850077/165646701-87e0722d-b22b-42f6-b59c-aeeba948bfcc.png)
![image](https://user-images.githubusercontent.com/77850077/165646740-c599ab91-90ad-4e88-b227-c3c20ee0c300.png)

**Comment by revenz** [comment]
fixed.
