### ISSUE TITLE
Support for not http(s) links

### ISSUE THREAD

**Issue by Frooodle** [revenz/Fenrus#90]
Fenrus Links to support none http(s) calls such as
file://
file:///
ftp:// 
(note both double and triple / )
etc 
![image](https://user-images.githubusercontent.com/77850077/168450369-7ff5394b-1b46-497d-aa0f-85ed7a575daa.png)

**Comment by revenz** [comment]
eased the regex to urls, now can be anything followed by :// and an optional third /
