### ISSUE TITLE
Feature Request: Single click dash change

### ISSUE THREAD

**Issue by OptimusGREEN** [revenz/Fenrus#94]
Hi, 

First of all, great project, my fave dash so far so well done.

I would love to be able to switch dash by one click or at max two click. Its currently 3 clicks opening the settings then trying to hit the small arrow at the dahboard drop down then clicking the dashboard.

I figured you could make clicking the name in the top left open a dahboard dropdown?

Thanks again.

**Comment by revenz** [comment]
added and pushed to docker hub.
