### ISSUE TITLE
Fenrus page stuck on "launching xy" splash screen

### ISSUE THREAD

**Issue by IceFlom** [revenz/Fenrus#95]
I have the same problem described in issue#51. I have set the link target to "Open in this tab". When I click on an app and then going back in the browser, I have the "Launching xyz..." splash screen and the page is unusable. A manual refresh of the page is then necessary.
If I click a link with the middle button on the mouse (= open in new tab), I have the app in a new tab and on the Fenrus page again the blocking splash screen.

A way to completely disable this hint window would be very good.

OS: macOS 12.4
Browsers: 
- Safari 15.5 (17613.2.7.1.8)
- Brave (Version 1.41.96 Chromium: 103.0.5060.114 (Offizieller Build) (arm64))

Not reproducible on:
- Firefox (102.0.1 (64-Bit))

**Comment by revenz** [comment]
fixed in dotnet rewrite
